service: notes-api-ts-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  environment:
    NOTES_API_TABLE_NAME: ${self:custom.NotesAPITable.name}
  iamRoleStatements:
    - ${file(infra/iam/NotesAPITableIAM.yml):NotesAPITableIAM}

resources:
  Resources:
    NotesAPITable: ${file(infra/resources/NotesAPITable.yml):NotesAPITable}

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello
          cors: true

  addNote:
    handler: src/handlers/addNote.handler
    events:
      - http:
          method: POST
          path: /note
          cors: true

  getNote:
    handler: src/handlers/getNote.handler
    events:
      - http:
          method: GET
          path: /note/{id}
          cors: true

custom:
  NotesAPITable:
    name: !Ref NotesAPITable
    arn: !GetAtt NotesAPITable.Arn
  bundle:
    linting: false
