NotesAPITable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: NotesAPITable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
