NotesAPITable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: NotesAPITable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: noteId
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
    KeySchema:
      - AttributeName: noteId
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: createdDate
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
