NotesAPITable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: NotesAPITable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: noteId
        AttributeType: S
    KeySchema:
      - AttributeName: noteId
        KeyType: HASH
